version: "3.1"
services:
  api-services:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
  mongo_db:
    image: mongo
    restart: always
    ports:
      - '37017:27017'

